// flow-typed signature: f290755eecf5f831871e0cf8e897ccae
// flow-typed version: <<STUB>>/jest-matcher-utils_v^27.4.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-matcher-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-matcher-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-matcher-utils/build/deepCyclicCopyReplaceable' {
  declare module.exports: any;
}

declare module 'jest-matcher-utils/build' {
  declare module.exports: any;
}

declare module 'jest-matcher-utils/build/Replaceable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-matcher-utils/build/deepCyclicCopyReplaceable.js' {
  declare module.exports: $Exports<'jest-matcher-utils/build/deepCyclicCopyReplaceable'>;
}
declare module 'jest-matcher-utils/build/index' {
  declare module.exports: $Exports<'jest-matcher-utils/build'>;
}
declare module 'jest-matcher-utils/build/index.js' {
  declare module.exports: $Exports<'jest-matcher-utils/build'>;
}
declare module 'jest-matcher-utils/build/Replaceable.js' {
  declare module.exports: $Exports<'jest-matcher-utils/build/Replaceable'>;
}
