// flow-typed signature: b67db888368f2107486b3c0e451aa895
// flow-typed version: <<STUB>>/level_v^7.0.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'level'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'level' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'level/browser' {
  declare module.exports: any;
}

declare module 'level/level' {
  declare module.exports: any;
}

// Filename aliases
declare module 'level/browser.js' {
  declare module.exports: $Exports<'level/browser'>;
}
declare module 'level/level.js' {
  declare module.exports: $Exports<'level/level'>;
}
